FROM a0bc4dee75e4
WORKDIR /
ADD HelloWorldApp-1.jar HelloWorldApp-1.jar
EXPOSE 8080
CMD ["java", "-jar", "HelloWorldApp-1.jar"]
RUN ECHO "Pipeline Succeded!!!"
#ENTRYPOINT ["java","-jar","HelloWorldApp-1.jar"]
