node 
{
   def mvnHome
   def currentDirectory
   def jarPath
   def app
   stage('Git Clone') 
    {       
      git 'https://github.com/KeerthigaM/HelloWorldDevOps.git'
      mvnHome = tool 'Maven3'
    }
    stage('Maven Build')
    {
       currentDirectory = pwd() + '\\HelloWorldApp'
        dir(currentDirectory)
        {
             if (isUnix()) {
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
             } else {
                bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
             }
        }
    }
    stage('Build Results') 
    {
      archive 'target/*.jar'
    }
    stage('Nexus Publish') 
    {
     jarPath = currentDirectory + '\\target\\HelloWorldApp-1.jar'        
     nexusPublisher nexusInstanceId: 'localnexus', nexusRepositoryId: 'releases', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: jarPath]], mavenCoordinate: [artifactId: 'HelloWorldApp', groupId: 'com', packaging: 'jar', version: '1']]]
    }
    stage('Build Image')
    {
        currentDirectory = pwd() + '\\HelloWorldApp'
        dir(currentDirectory)
        {         
         bat 'docker build -t helloworld3 .'
         bat 'docker run helloworld3'
        }
    }
}
